### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Saiki-san** [Saiki-san/furima-31631#9]
# 自身のフリマアプリのURL | 本番環境(Heroku)のURL
　https://furima-31631.herokuapp.com/
# Basic認証のIDとパスワード |
　ID：admin、パスワード：2222
# 出品者用のメールアドレスとパスワード | 本番環境にて商品出品しているユーザーの情報
　メールアドレス：test@test.com、パスワード：aaa111
# 購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
　メールアドレス：sample@sample.com、パスワード：aaa111
# 購入用カードの番号・期限・セキュリティコード | PAY.JPのテストカード情報
　カード番号　　　　：4242424242424242
　期限　　　　　　　：12.24
　セキュリティコード：123

**Comment by MoonMaker23** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
・購入用アカウントにて「購入画面に進む」をクリックした所、添付のエラー画面に遷移しました。
　購入画面に遷移するよう修正をお願い致します。
![image](https://user-images.githubusercontent.com/69611629/100419610-3ecac280-30c8-11eb-89a4-81b0c7bf5d1c.png)

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Saiki-san** [comment]
修正完了致しました。
お忙しいところ恐れ入りますが、再度ご確認の程、
宜しくお願い致します。

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
前回の修正項目は修正されておりました。ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・未ログイン時にも出品ボタンを押すと出品ページに遷移してしまいます。こちら未ログイン時にはログインページに遷移するように修正をお願いします。

・未ログインときに、直接編集ページのURLを入力すると添付画像のようなエラーが出てしまいます。こちらエラー画面が出ずに、ログインページに遷移するように修正をお願いします。

・ログイン時に他ユーザーの投稿した商品編集ページのURLを入力すると、そのまま編集ページに遷移してしまいます。こちらトップページに遷移するように修正をお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

<img width="554" alt="スクリーンショット 2020-11-27 16 19 31" src="https://user-images.githubusercontent.com/57244739/100422885-7472aa00-30ce-11eb-9418-32fe0d16c89d.png">

**Comment by Saiki-san** [comment]
度々恐れ入ります。
再修正完了致しましたので、
ご確認の程、宜しくお願い致します。

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
一部修正の確認ができました。ありがとうございます。
以下の点について再度ご確認いただき修正をお願い致します！

[修正箇所]
・ログイン時に他ユーザーの商品編集ページ、購入済み商品の編集ページのURLを直接入力すると、そのまま編集ページに遷移してしまいます。こちらトップページに遷移するように修正をお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Saiki-san** [comment]
度々恐れ入ります。
再修正完了致しましたので、
ご確認の程、宜しくお願い致します。

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by Saiki-san** [comment]
ありがとうございます！
今後もよりいっそう　技術的理解に努めて参りたいと思います！
